image: archlinux
packages:
    - go
sources:
    - 'https://github.com/arborchat/muscadine/'
environment:
    GO111MODULE: "on"
tasks:
    - test: |
        cd muscadine
        go test -v -cover ./...
